name: Accessibility Tests 

on: push

jobs:
  accessibility-test:
    name: Run Accessibility Tests
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    services:
      db:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTRGES_DB: launch_cart_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup App
        uses: ./.github/workflows/setup
      - name: Run Accessibility Tests
        run: |
          mix ecto.setup --no-compile
          mix run priv/repo/seeds.test.exs --no-compile
          mix phx.server &
          sleep 10
          npm run test-pa11y --prefix assets
          pkill -9 beam.smp
          mix ecto.drop --no-compile
